#!/bin/bash

gitbook build .
rm -rf /tmp/gitbook
mkdir -p /tmp/gitbook
cp -rf _book/* /tmp/gitbook
cp CNAME /tmp/gitbook
cp -f favicon.ico /tmp/gitbook/gitbook/images
cd /tmp/gitbook
git init
git remote add origin git@github.com:talkincode/ToughRADIUS-GitBook.git
git add .
git commit -am "deploy gitbook `date +%Y-%m-%d" "%H:%M:%S`"
git push -f origin master:gh-pages